### ISSUE TITLE
What License OFL or Apache?

### ISSUE THREAD

**Issue by m4rc1e** [vahanhovh/mardoto#3]
ping @davelab6

repo currently uses Roboto's Apache license.

**Comment by davelab6** [comment]
Apache better as an exception

**Comment by m4rc1e** [comment]
Thank you.

Can I still keep our usual copyright string in these fonts,`Copyright 2017 The Mardoto Project Authors (https://github.com/vahanhovh/mardoto)`?

**Comment by davelab6** [comment]
Yes
